// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBDk2uLwETcEANf-Yu06bOV-cfbk0AVE',
    appId: '1:507875304942:web:d5cb6c44bb2c7c0e0b9aff',
    messagingSenderId: '507875304942',
    projectId: 'resturanttask-e1ad9',
    authDomain: 'resturanttask-e1ad9.firebaseapp.com',
    storageBucket: 'resturanttask-e1ad9.firebasestorage.app',
    measurementId: 'G-HJ31MQDBHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-HxlBU_eKARzp8inBWoQsCSQWccrrVbE',
    appId: '1:507875304942:android:c45db3192e8271720b9aff',
    messagingSenderId: '507875304942',
    projectId: 'resturanttask-e1ad9',
    storageBucket: 'resturanttask-e1ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxdMVC55e7okkVEoL9cFmsfJGlDh0K9K0',
    appId: '1:507875304942:ios:d7ce3247ca7da7a40b9aff',
    messagingSenderId: '507875304942',
    projectId: 'resturanttask-e1ad9',
    storageBucket: 'resturanttask-e1ad9.firebasestorage.app',
    iosBundleId: 'com.example.resturantTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxdMVC55e7okkVEoL9cFmsfJGlDh0K9K0',
    appId: '1:507875304942:ios:d7ce3247ca7da7a40b9aff',
    messagingSenderId: '507875304942',
    projectId: 'resturanttask-e1ad9',
    storageBucket: 'resturanttask-e1ad9.firebasestorage.app',
    iosBundleId: 'com.example.resturantTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLBDk2uLwETcEANf-Yu06bOV-cfbk0AVE',
    appId: '1:507875304942:web:79c0a929443c57550b9aff',
    messagingSenderId: '507875304942',
    projectId: 'resturanttask-e1ad9',
    authDomain: 'resturanttask-e1ad9.firebaseapp.com',
    storageBucket: 'resturanttask-e1ad9.firebasestorage.app',
    measurementId: 'G-DEPLW63B1B',
  );
}
