name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 💙 Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6' # Or any stable version you're using
        channel: 'stable'

    - name: 🧪 Install dependencies
      run: flutter pub get

    - name: ✅ Analyze
      run: flutter analyze

    - name: 🧪 Run tests
      run: flutter test
