name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.34.0-0.1.pre'
          channel: 'beta'


      # Install dependencies
      - name: Install dependencies
        run: flutter pub get


      # Build APK (for Android)
      - name: Build APK
        run: flutter build apk --release
